image:
  repository: glikson/wdmon
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: ""
  hosts:
    - host: wdmon.local
      paths:
        - path: /
          pathType: Prefix
