apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-wdmon
  labels:
    app: wdmon
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: wdmon
  template:
    metadata:
      labels:
        app: wdmon
    spec:
      serviceAccountName: {{ .Release.Name }}-wdmon
      terminationGracePeriodSeconds: 10
      containers:
        - name: wdmon
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          terminationMessagePath: /dev/termination-log
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: FLASK_RUN_HOST
              value: "0.0.0.0"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
