apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-wdmon
  labels:
    app: wdmon
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-wdmon
  labels:
    app: wdmon
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-wdmon
  labels:
    app: wdmon
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-wdmon
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-wdmon
    namespace: {{ .Release.Namespace }}
